### PR TITLE
Append registration data to build

### PR DESCRIPTION
**Pull request by CodedOre**
**Merge when the next update happens!**

Include the key and secret for Cawbird into the manifest to enable building it. \
Includes some updates to our dependencies.

### CODE REVIEW

**Comment by IBBoard** [comment]
@CodedOre I've updated the tag and put it on its own keys (for new accounts). Can you test it so I can merge it?

**Comment by CodedOre** [comment]
Seems good to me on my system. Should be ready for merge.

**Comment by CodedOre** [comment]
I just check the dependencies quick...

**Comment by CodedOre** [comment]
Alright, no new updates to our dependencies, then it is good to go!

**Pull request merged**
